#!/bin/bash
#################################################################################
# Module     :  mis_coded_blank_wire.sh
# Description:  Calls the mis_coded_bank_wire.pl program to generate the 
#               "Mis_Coded_Blank_Wire.rpt" Data Integrity Report.
#               Runs from daily, weekly, or monthly cron process by copying this
#               file to the /etc/cron.rmpc.daily, weekly, or monthly directory
#################################################################################
# -------------------------------------------------------------------
# Program History:
# INT  DATE      Comments
# ---  --------  --------
# DLW  20050607  Created 
# DLW  20070502  Moved the reports from the reports directory to it_reports
# DLW  20151110  Copied from aurora to rufus and Modified for Postgres/New Server
# DLW  20210601  Replace ftp link with https
# DLW  20241011  Changed #!/bin/sh #!/bin/bash above
#****************************************************************************
TMPFILE=/tmp/mis_coded_blank_wire_rpt$$
#. /home/rmpcdb/.bash_profile > $TMPFILE 2>&1
. /usr/local/bin/set_env_vars.sh
mis_coded_blank_wire_rpt.pl > $TMPFILE 2>&1
#echo "Report at: ftp://ftp.rmis.org/pub/it_reports/Mis_Coded_Blank_Wire.rpt" > $TMPFILE 2>&1
echo "Report at: https://www.rmpc.org/pub/di_reports/Mis_Coded_Blank_Wire.rpt" > $TMPFILE 2>&1
if [ -s $TMPFILE ]; then 
  mail -s "Data Integrity Report: Mis_Coded_Blank_Wire output " rmpcdb.admin@psmfc.org < $TMPFILE 
fi
rm -f  $TMPFILE
